export const stats = [
  { value: 6.9, decimals: 1, suffix: 'M+', label: 'Followers', platform: 'TikTok' },
  { value: 3.2, decimals: 1, suffix: 'M+', label: 'Subscribers', platform: 'YouTube' },
  { value: 7.6, decimals: 1, suffix: 'B+', label: 'Total Views', platform: 'YouTube' },
  { value: 27, decimals: 0, suffix: 'K+', label: 'Members', platform: 'Discord' },
]

export const platforms = [
  {
    index: '01',
    name: 'YouTube',
    handle: '@actuallycarterpcs',
    meta: '3.2M subscribers',
    description: 'Long-form builds, deep dives, chaos.',
    href: 'https://youtube.com/@actuallycarterpcs',
    external: true,
  },
  {
    index: '02',
    name: 'TikTok',
    handle: '@carterpcs',
    meta: '6.9M followers',
    description: 'Four drops a day. Every day.',
    href: 'https://tiktok.com/@carterpcs',
    external: true,
  },
  {
    index: '03',
    name: 'Instagram',
    handle: '@carterpcs_',
    meta: 'Photos & stories',
    description: 'Behind the scenes and setups.',
    href: 'https://instagram.com/carterpcs_',
    external: true,
  },
  {
    index: '04',
    name: 'Discord',
    handle: "Carter's Cacti",
    meta: '27K members',
    description: 'The community. Builds, drops, drama.',
    href: '#community',
    external: false,
  },
  {
    index: '05',
    name: 'Linktree',
    handle: 'linktree.com/carterpcs',
    meta: 'Everything else',
    description: 'Every link in one place.',
    href: 'https://linktree.com/carterpcs',
    external: true,
  },
  {
    index: '06',
    name: 'Business',
    handle: 'carterpcs@rakugomedia.com',
    meta: 'Sponsorships & collabs',
    description: 'Serious inquiries only.',
    href: 'mailto:carterpcs@rakugomedia.com',
    external: false,
  },
]

export const videos = [
  {
    index: '001',
    title: 'I Built the Stupidest PC Ever',
    platform: 'YouTube',
    duration: '12:34',
    views: '2.1M',
    date: '2 days ago',
    href: 'https://youtube.com/@actuallycarterpcs',
  },
  {
    index: '002',
    title: 'This Phone Broke Me',
    platform: 'TikTok',
    duration: '0:58',
    views: '5.4M',
    date: '3 days ago',
    href: 'https://tiktok.com/@carterpcs',
  },
  {
    index: '003',
    title: 'Testing $50,000 Gaming Setups',
    platform: 'YouTube',
    duration: '15:42',
    views: '1.8M',
    date: '5 days ago',
    href: 'https://youtube.com/@actuallycarterpcs',
  },
  {
    index: '004',
    title: 'Apple Just Changed Everything',
    platform: 'TikTok',
    duration: '0:45',
    views: '8.2M',
    date: '1 week ago',
    href: 'https://tiktok.com/@carterpcs',
  },
  {
    index: '005',
    title: 'The Worst Tech Fails of 2024',
    platform: 'YouTube',
    duration: '18:21',
    views: '3.1M',
    date: '1 week ago',
    href: 'https://youtube.com/@actuallycarterpcs',
  },
  {
    index: '006',
    title: 'I Bought Every iPhone Ever Made',
    platform: 'YouTube',
    duration: '22:10',
    views: '4.7M',
    date: '2 weeks ago',
    href: 'https://youtube.com/@actuallycarterpcs',
  },
]

export const links = {
  youtube: 'https://youtube.com/@actuallycarterpcs',
  tiktok: 'https://tiktok.com/@carterpcs',
  instagram: 'https://instagram.com/carterpcs_',
  linktree: 'https://linktree.com/carterpcs',
  email: 'mailto:carterpcs@rakugomedia.com',
}
